Queen Bee‚Äôs Pattern Parade: 
üëëüêù The Queen Bee is on a mission to find the sweetest bee names with the best patterns! while SAS flexed its data-handling muscles to reveal hidden patterns, watch as Python weaves its web of regex wizadry. Which tool will uncover the juiciest insights or are they both equal? Let the name hunt begin!

Find all instances of bee names ending in 'en' 'ed' or with a '-' using perl regular expression. A RegEx, or Regular Expression, is a sequence of characters that forms a search pattern.

RegEx can be used to check if a string contains the specified search pattern.

In [1]:
import pandas as pd
import re

# Read the scientific and common name lookup csv file into a DataFrame
df3=pd.read_csv('/workspaces/myfolder/SASPythonDataScientists/Bumblebee_Others_Scientific_Common_Names.csv' , encoding='latin-1')

In [2]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ScientificName   162 non-null    object
 1   Species          162 non-null    object
 2   specificEpithet  156 non-null    object
 3   CommonName       162 non-null    object
 4   Description      161 non-null    object
 5   Source           161 non-null    object
dtypes: object(6)
memory usage: 7.7+ KB

DataFrames can be filtered in multiple ways; the most intuitive of which boolean indexing creating a series of True/False values.

In [3]:
# Regular expression pattern
pattern = r'((ed|ern)\W)|-'

# Subset the DataFrame based on the regex pattern
df_regex = df3[df3['CommonName'].str.contains(pattern, regex=True)]

# Display the filtered DataFrame
print(df_regex)

               ScientificName       Species   specificEpithet  \
4       Agapostemon virescens   Agapostemon         virescens
23             Apis mellifera          Apis         mellifera
28             Bombus affinis        Bombus           affinis
29           Bombus appositus        Bombus         appositus
33           Bombus balteatus        Bombus         balteatus
34            Bombus bifarius        Bombus          bifarius
35         Bombus bimaculatus        Bombus       bimaculatus
37            Bombus borealis        Bombus          borealis
47          Bombus flavifrons        Bombus        flavifrons
49           Bombus fraternus        Bombus         fraternus
51        Bombus griseocollis        Bombus      griseocollis
54           Bombus impatiens        Bombus         impatiens
57             Bombus lucorum        Bombus           lucorum
58         Bombus melanopygus        Bombus       melanopygus
59              Bombus mixtus        Bombus            mixtus
63        Bombus occidentalis        Bombus      occidentalis
67         Bombus rotundiceps        Bombus       rotundiceps
68         Bombus rufocinctus        Bombus       rufocinctus
74           Bombus ternarius        Bombus         ternarius
75          Bombus terrestris        Bombus        terrestris
76           Bombus terricola        Bombus         terricola
77              Bombus vagans        Bombus            vagans
80        Bombus vosnesenskii        Bombus      vosnesenskii
84         Ceratina calcarata      Ceratina         calcarata
85             Ceratina dupla      Ceratina             dupla
88      Coelioxys octodentata     Coelioxys       octodentata
90              Eucera hamata        Eucera            hamata
91          Halictus confusus      Halictus          confusus
94        Halictus rubicundus      Halictus        rubicundus
95          Heriades carinata      Heriades          carinata
96       Hoplitis pilosifrons      Hoplitis       pilosifrons
98          Hoplitis truncata      Hoplitis          truncata
99   Hylaeus affinis/modestus       Hylaeus  affinis/modestus
100          Hylaeus modestus       Hylaeus          modestus
112   Lasioglossum fuscipenne  Lasioglossum        fuscipenne
116  Lasioglossum leucozonium  Lasioglossum       leucozonium
127          Megachile brevis     Megachile            brevis
128          Megachile exilis     Megachile            exilis
129          Megachile gemula     Megachile            gemula
133       Megachile montivaga     Megachile         montivaga
136                Melissodes    Melissodes               NaN
137     Melissodes bimaculata    Melissodes        bimaculata
138     Melissodes comptoides    Melissodes        comptoides
139    Melissodes denticulata    Melissodes       denticulata
140       Melissodes desponsa    Melissodes          desponsa
141      Melissodes subillata    Melissodes         subillata
142       Melissodes trinodis    Melissodes          trinodis
145         Nomada articulata        Nomada        articulata
146          Nomada australis        Nomada         australis
147          Nomada bidentata        Nomada         bidentata
148        Nomada denticulata        Nomada       denticulata
151           Nomada maculata        Nomada          maculata
156         Osmia atriventris         Osmia       atriventris
157           Osmia bucephala         Osmia         bucephala

                         CommonName  \
4       Bicolored Striped Sweat Bee
23                Western Honey Bee
28          Rusty Patched Bumblebee
29       White-shouldered Bumblebee
33          Golden-belted Bumblebee
34               Two-form Bumblebee
35            Two-spotted Bumblebee
37         Northern Amber Bumblebee
47         Yellow-fronted Bumblebee
49        Southern Plains Bumblebee
51           Brown-belted Bumblebee
54         Common Eastern Bumblebee
57           White-tailed Bumblebee
58          Orange-rumped Bumblebee
59           Fuzzy-horned Bumblebee
63                Western Bumblebee
67           Round-headed Bumblebee
68             Red-belted Bumblebee
74            Tri-colored Bumblebee
75            Buff-tailed Bumblebee
76          Yellow-banded Bumblebee
77             Half-black Bumblebee
80           Yellow-faced Bumblebee
84                 Spurred Ceratina
85                 Doubled Ceratina
88         Eight-toothed Cuckoo Bee
90                    Hooked Eucera
91               Confused Sweat Bee
94           Broad-banded Sweat Bee
95                  Keeled Heriades
96             Hairy-faced Hoplitis
98               Truncated Hoplitis
99                Modest Masked Bee
100               Modest Masked Bee
112          Dusky-winged Sweat Bee
116          White-banded Sweat Bee
127                Short-leafed Bee
128              Slender-leafed Bee
129           Gemmed Leafcutter Bee
133  Mountain-loving Leafcutter Bee
136                 Long-horned Bee
137     Two-spotted Long-horned Bee
138    Well-behaved Long-horned Bee
139       Toothless Long-horned Bee
140      Despondent Long-horned Bee
141             Slightly Horned Bee
142   Three-knobbed Long-horned Bee
145          Articulated Cuckoo Bee
146             Southern Cuckoo Bee
147          Two-toothed Cuckoo Bee
148              Toothed Cuckoo Bee
151              Spotted Cuckoo Bee
156         Black-bellied Mason Bee
157          Large-headed Mason Bee

                                           Description  \
4    Widespread in North America; favors asters and...
23   Found globally; enjoys a wide range of flowers...
28   Found in the eastern U.S.; favors wildflowers ...
29   Found in woodlands and gardens; enjoys clover ...
33   Found in western U.S.; prefers wildflowers and...
34   Found in various North American habitats; enjo...
35   Found in northeastern U.S.; enjoys clover and ...
37   Found in northern U.S. and Canada; enjoys wild...
47   Found in U.S.; enjoys wildflowers and garden p...
49   Found in southern U.S.; enjoys a variety of wi...
51   Found in eastern U.S.; enjoys clover and meado...
54   Found in eastern U.S.; enjoys a wide range of ...
57   Found in Europe and Asia; enjoys clover and me...
58   Found in Europe and Asia; enjoys wildflowers a...
59   Found in U.S.; enjoys a variety of flowering p...
63   Found in western U.S.; enjoys wildflowers and ...
67   Found in Europe and Asia; prefers wildflowers ...
68   Found in Europe and Asia; enjoys clover and me...
74   Found in North America; enjoys wildflowers and...
75   Found in Europe and Asia; enjoys wildflowers a...
76   Found in northern U.S. and Canada; prefers wil...
77   Found in the U.S.; enjoys wildflowers and gard...
80   Found in North America; enjoys a variety of fl...
84   Found in gardens and fields; favors small flow...
85   Found in gardens and urban areas; enjoys small...
88   Found in U.S.; parasitizes nests of other bees...
90   Found in western U.S.; enjoys wildflowers and ...
91   Found in gardens and fields; favors asters and...
94   Found in U.S.; enjoys sunflowers and goldenrod...
95   Found in woodlands and fields; enjoys small fl...
96   Found in meadows and forests; enjoys small flo...
98   Found in western U.S.; favors small flowers; a...
99   Found in gardens and urban areas; enjoys small...
100  Found in gardens and urban areas; enjoys small...
112  Found in gardens and fields; enjoys asters and...
116  Found in U.S.; enjoys sunflowers and goldenrod...
127  Found in U.S.; enjoys a variety of flowering p...
128  Found in various U.S. habitats; enjoys small f...
129  Found in meadows and forests; enjoys a variety...
133  Found in western U.S.; prefers wildflowers and...
136  Found in gardens and meadows; favors wildflowe...
137  Found in western U.S.; enjoys wildflowers and ...
138  Found in U.S.; favors wildflowers and garden p...
139  Found in U.S.; prefers wildflowers and garden ...
140  Found in U.S.; enjoys wildflowers and garden p...
141  Found in U.S.; enjoys wildflowers and garden p...
142  Found in U.S.; favors wildflowers and garden p...
145  Found in U.S.; parasitizes nests of other bees...
146  Found in southeastern U.S.; parasitizes nests ...
147  Found in northeastern U.S.; parasitizes nests ...
148  Found in U.S.; parasitizes nests of other bees...
151  Found in northeastern U.S.; parasitizes nests ...
156  Found in woodlands and fields; enjoys small fl...
157  Found in western U.S.; enjoys small flowers; a...

                                             Source
4                                     Discover Life
23                                    Discover Life
28                                    IUCN Red List
29                      Bumblebees of North America
33                      Bumblebees of North America
34                      Bumblebees of North America
35                      Bumblebees of North America
37                      Bumblebees of North America
47                      Bumblebees of North America
49                      Bumblebees of North America
51                      Bumblebees of North America
54                      Bumblebees of North America
57                      Bumblebees of North America
58                      Bumblebees of North America
59                      Bumblebees of North America
63                                    IUCN Red List
67   Integrated Taxonomic Information System (ITIS)
68                      Bumblebees of North America
74                      Bumblebees of North America
75                      Bumblebees of North America
76                                    IUCN Red List
77                      Bumblebees of North America
80                      Bumblebees of North America
84                                         BugGuide
85                                         BugGuide
88                                         BugGuide
90                                    Discover Life
91                                    Discover Life
94                                         BugGuide
95                                         BugGuide
96                                    Discover Life
98                                    Discover Life
99                                    Discover Life
100                                   Discover Life
112                                        BugGuide
116                                   Discover Life
127                                   Discover Life
128                                        BugGuide
129                                   Discover Life
133                                   Discover Life
136                                   Discover Life
137                                   Discover Life
138                                        BugGuide
139                                        BugGuide
140                                   Discover Life
141                                        BugGuide
142                                        BugGuide
145                                   Discover Life
146                                   Discover Life
147                                        BugGuide
148                                   Discover Life
151                                   Discover Life
156                                   Discover Life
157                                        BugGuide

/tmp/ipykernel_10983/226254587.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_regex = df3[df3['CommonName'].str.contains(pattern, regex=True)]

In [4]:
df_regex.shape

(54, 6)

Detailed Explanation
df3['CommonName'].str.contains(pattern, regex=True): This function is used to generate a Boolean mask based on whether each entry in the commonname column matches the pattern.

df3['CommonName']: This selects the commonname column from the DataFrame df3.
.str.contains(pattern, regex=True): This method checks each entry in the commonname column to see if it contains a substring that matches the regular expression pattern(defined earlier).
regex=True: This argument ensures that the pattern is treated as a regular expression. It‚Äôs the default value, so it‚Äôs optional but included here for clarity.
df3[...]:
The Boolean Series returned by str.contains() (which is True or False for each row) is used to filter df3.
df3[df3['commonname'].str.contains(pattern, regex=True)]: filters the DataFrame df3 to include only the rows where the commonname matches the regex pattern.

### Grouping Aggregating Data

In [2]:
import pandas as pd
# Read the North American bumblebee CSV file into a DataFrame for easy data manipulation and analysis.

df1=pd.read_csv('/workspaces/myfolder/SASPythonDataScientists/pattern_decline_N_American_Bumblebees.csv', encoding='latin-1')

/tmp/ipykernel_23440/2948246206.py:4: DtypeWarning: Columns (6,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv('/workspaces/myfolder/SASPythonDataScientists/pattern_decline_N_American_Bumblebees.csv', encoding='latin-1')

In [24]:
df1.groupby(['scientificName','stateProvince']).size().reset_index(name='count').sort_values(by='count', ascending=False).head(20)

           scientificName stateProvince  count
629   Bombus vosnesenskii    California   8982
85        Bombus bifarius    California   2950
94        Bombus bifarius          Utah   2392
557      Bombus terricola      Michigan   2185
306      Bombus impatiens      Illinois   1723
410   Bombus occidentalis    California   1712
86        Bombus bifarius      Colorado   1594
634   Bombus vosnesenskii        Oregon   1588
92        Bombus bifarius        Oregon   1555
95        Bombus bifarius    Washington   1189
436  Bombus pensylvanicus      Illinois   1097
466  Bombus pensylvanicus         Texas   1071
96        Bombus bifarius       Wyoming   1016
270   Bombus griseocollis      Nebraska    947
424   Bombus occidentalis    Washington    937
87        Bombus bifarius         Idaho    935
449  Bombus pensylvanicus      Nebraska    880
421   Bombus occidentalis        Oregon    829
423   Bombus occidentalis          Utah    824
565      Bombus terricola      New York    813

Pandas describe() to view a statistical summary of a dataframe like percentile, mean, std, etc. of a data frame or a series of numeric values

In [33]:
#summary statistics
df1.describe()

,id,occurrenceID,year,month,day,verbatimLatitude,verbatimLongitude
count,66907.000000,6.690700e+04,65778.000000,66368.000000,63897.000000,65980.000000,65980.000000
mean,33454.000000,7.382750e+08,1964.989845,6.833941,14.933080,40.935030,-102.363015
std,19314.531567,3.349292e+07,42.751260,2.184931,9.321771,3.910773,16.332720
min,1.000000,6.993850e+08,39.000000,0.000000,0.000000,25.297440,-125.795040
25%,16727.500000,6.994017e+08,1940.000000,6.000000,7.000000,38.340950,-119.822525
50%,33454.000000,7.671145e+08,1967.000000,7.000000,15.000000,40.867000,-102.870000
75%,50180.500000,7.671326e+08,1996.000000,8.000000,23.000000,43.402905,-88.564530
max,66907.000000,7.671517e+08,2011.000000,12.000000,31.000000,87.751000,-57.429150